import math
print(math.sqrt(4))
print(math.ceil(1.5))
print(math.floor(1.5))
print(math.factorial(5))
print(math.fabs(-5))
print(math.pow(2,5))
print(math.log2(2))
print(math.log10(2))
print(math.pi)
print(math.e)
print(math.degrees(45))
print(math.round(5.56))