name={"vignes","ram","ravi"}
name.add("arun")
print(name)
a={"kumar","sunder","boss"}
name.update(a)
print(name)
name.remove("sunder")
print(name)
name.discard("ram")
print(name)
name.pop
print(name)
name.clear
print(name)
c={1,3,2,4,6,7,}
d={1,10,5,8,6,7}
e=c.intersection(d)
f=c.symmetric_difference(d)
print(e)
print(f)
g=c.isdisjoint(d)
n=c.issubset(d)
k=c.issubset(d)
print(g)
print(n)
print(k)